import {DatabaseSync} from 'node:sqlite';
import {randomBytes,randomInt,createHash} from 'node:crypto';
export const hash=s=>createHash('sha256').update(s).digest('hex');
export const token=()=>randomBytes(32).toString('hex');
export const PRICES={7:99,30:299,90:499};
export const VERSION='2026-09-25';
export function code(){const abc='abcdefghjkmnpqrstuvwxyz23456789';const s=Array.from({length:8},()=>abc[randomInt(abc.length)]).join('');return s.slice(0,4)+'-'+s.slice(4);}
export class Store{
 constructor(file,now=Date.now){this.now=now;this.db=new DatabaseSync(file);this.db.exec(`
 PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS users(uuid TEXT PRIMARY KEY,name TEXT NOT NULL,created INTEGER NOT NULL,discount TEXT UNIQUE NOT NULL,plus_until INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS issued_codes(hash TEXT PRIMARY KEY);
 CREATE TABLE IF NOT EXISTS challenges(hash TEXT PRIMARY KEY,browser TEXT UNIQUE NOT NULL,expires INTEGER NOT NULL,uuid TEXT,consumed INTEGER NOT NULL DEFAULT 0,accepted INTEGER NOT NULL,terms TEXT NOT NULL,privacy TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,uuid TEXT NOT NULL REFERENCES users(uuid),expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS consent(uuid TEXT NOT NULL,accepted INTEGER NOT NULL,terms TEXT NOT NULL,privacy TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS nonces(nonce TEXT PRIMARY KEY,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS server_status(id INTEGER PRIMARY KEY CHECK(id=1),payload TEXT NOT NULL,received INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,uuid TEXT NOT NULL REFERENCES users(uuid),days INTEGER NOT NULL,amount INTEGER NOT NULL,discounted INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'creating',provider_id TEXT UNIQUE,payment_id TEXT UNIQUE,created INTEGER NOT NULL,delivery_until INTEGER,delivered INTEGER,consented INTEGER NOT NULL);
 CREATE UNIQUE INDEX IF NOT EXISTS one_discount_per_player ON orders(uuid) WHERE discounted=1;
 CREATE INDEX IF NOT EXISTS orders_by_user ON orders(uuid,created);
 CREATE INDEX IF NOT EXISTS delivery_queue ON orders(status,created);
 CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
 `);}
 transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const v=fn();this.db.exec('COMMIT');return v;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 rate(key,max,window){return this.transaction(()=>{const now=this.now();this.db.prepare('DELETE FROM rate_limits WHERE expires<?').run(now);const row=this.db.prepare('SELECT count FROM rate_limits WHERE key=?').get(key);if(row&&row.count>=max)return false;this.db.prepare('INSERT INTO rate_limits VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').run(key,now+window);return true;});}
 challenge(){return this.transaction(()=>{let value;for(let i=0;i<20;i++){value=code();if(this.db.prepare('INSERT OR IGNORE INTO issued_codes VALUES(?)').run(hash(value)).changes)break;value=null;}if(!value)throw Error('Unable to generate code');const browser=token(),now=this.now();this.db.prepare('INSERT INTO challenges(hash,browser,expires,accepted,terms,privacy) VALUES(?,?,?,?,?,?)').run(hash(value),hash(browser),now+600000,now,VERSION,VERSION);return {code:value,browser,expires:now+600000};});}
 verify(value,uuid,name){return this.transaction(()=>{const row=this.db.prepare('SELECT * FROM challenges WHERE hash=?').get(hash(value));if(!row||row.expires<=this.now()||row.consumed)return false;if(row.uuid)return row.uuid===uuid;this.db.prepare('INSERT INTO users(uuid,name,created,discount) VALUES(?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name').run(uuid,name,this.now(),'WELCOME-'+randomBytes(5).toString('hex').toUpperCase());this.db.prepare('UPDATE challenges SET uuid=? WHERE hash=? AND uuid IS NULL').run(uuid,hash(value));return true;});}
 poll(browser){return this.transaction(()=>{const row=this.db.prepare('SELECT * FROM challenges WHERE browser=?').get(hash(browser||''));if(!row||row.expires<=this.now()||row.consumed)return {expired:true};if(!row.uuid)return {pending:true};const session=token();this.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(session),row.uuid,this.now()+30*86400000);this.db.prepare('UPDATE challenges SET consumed=1 WHERE hash=?').run(row.hash);this.db.prepare('INSERT INTO consent VALUES(?,?,?,?)').run(row.uuid,row.accepted,row.terms,row.privacy);return {session,user:this.user(row.uuid)};});}
 session(t){const row=this.db.prepare('SELECT uuid FROM sessions WHERE hash=? AND expires>?').get(hash(t||''),this.now());return row?this.user(row.uuid):null;}
 logout(t){this.db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(t||''));}
 user(uuid){const u=this.db.prepare('SELECT * FROM users WHERE uuid=?').get(uuid);if(!u)return null;const spent=this.db.prepare("SELECT 1 FROM orders WHERE uuid=? AND discounted=1 AND status IN ('paid','delivered','refunded')").get(uuid);return {uuid:u.uuid,name:u.name,plusUntil:u.plus_until,discountCode:spent?null:u.discount,orders:this.db.prepare('SELECT id,days,amount,status FROM orders WHERE uuid=? ORDER BY created DESC LIMIT 15').all(uuid).map(o=>({...o,status:o.status==='creating'?'pending':o.status}))};}
 nonce(value){this.db.prepare('DELETE FROM nonces WHERE expires<?').run(this.now());return !!this.db.prepare('INSERT OR IGNORE INTO nonces VALUES(?,?)').run(value,this.now()+300000).changes;}
 heartbeat(payload){this.db.prepare('INSERT INTO server_status VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,received=excluded.received').run(JSON.stringify(payload),this.now());}
 status(address,bedrockPort){const row=this.db.prepare('SELECT * FROM server_status WHERE id=1').get();if(!row)return {state:'unavailable',online:null,max:null,address:address||null,bedrockPort,checkedAt:null};const p=JSON.parse(row.payload);const fresh=this.now()-row.received<=90000;return {state:fresh?(p.online?'online':'offline'):'stale',online:fresh&&p.online?p.players:null,max:fresh?p.max:null,address:address||null,bedrockPort,checkedAt:row.received,version:p.version};}
 order(uuid,days,discountCode){return this.transaction(()=>{if(!Object.hasOwn(PRICES,days))throw Error('Choose a valid Nugget+ duration.');const u=this.db.prepare('SELECT * FROM users WHERE uuid=?').get(uuid);const discounted=!!discountCode;if(discounted&&discountCode!==u.discount)throw Error('That discount does not belong to this account.');if(discounted){const old=this.db.prepare('SELECT * FROM orders WHERE uuid=? AND discounted=1').get(uuid);if(old){if(['paid','delivered','refunded'].includes(old.status))throw Error('Your welcome discount has already been used.');if(old.days!==days)throw Error(`Your discount is reserved for the ${old.days}-day checkout. Complete or retry that plan.`);return old;}}const old=this.db.prepare("SELECT * FROM orders WHERE uuid=? AND days=? AND discounted=? AND status IN ('creating','pending') ORDER BY created DESC LIMIT 1").get(uuid,days,Number(discounted));if(old)return old;const id=randomBytes(16).toString('hex');this.db.prepare('INSERT INTO orders(id,uuid,days,amount,discounted,created,consented) VALUES(?,?,?,?,?,?,?)').run(id,uuid,days,discounted?Math.round(PRICES[days]*.9):PRICES[days],Number(discounted),this.now(),this.now());return this.db.prepare('SELECT * FROM orders WHERE id=?').get(id);});}
 attach(id,providerId){this.db.prepare("UPDATE orders SET provider_id=?,status='pending' WHERE id=? AND provider_id IS NULL AND status='creating'").run(providerId,id);}
 captured(payment){return this.transaction(()=>{const o=this.db.prepare('SELECT * FROM orders WHERE provider_id=?').get(payment.order_id);if(!o||payment.status!=='captured'||payment.currency!=='USD'||payment.amount!==o.amount||!/^pay_[a-zA-Z0-9]+$/.test(payment.id))throw Error('Payment does not match a pending order.');if(['paid','delivered','refunded'].includes(o.status)){if(o.payment_id!==payment.id)throw Error('Order was settled with another payment');return o;}this.db.prepare("UPDATE orders SET status='paid',payment_id=? WHERE id=?").run(payment.id,o.id);return this.db.prepare('SELECT * FROM orders WHERE id=?').get(o.id);});}
 deliveries(){return this.db.prepare("SELECT id,uuid,days FROM orders WHERE status='paid' ORDER BY created LIMIT 25").all();}
 acknowledge(id,uuid,until){return this.transaction(()=>{const o=this.db.prepare('SELECT * FROM orders WHERE id=? AND uuid=?').get(id,uuid);if(!o||!['paid','delivered'].includes(o.status))throw Error('Delivery not found');if(o.status==='delivered')return;this.db.prepare("UPDATE orders SET status='delivered',delivery_until=?,delivered=? WHERE id=?").run(until,this.now(),id);this.db.prepare('UPDATE users SET plus_until=MAX(plus_until,?) WHERE uuid=?').run(until,uuid);});}
 clean(){this.db.prepare('DELETE FROM sessions WHERE expires<?').run(this.now());this.db.prepare('DELETE FROM challenges WHERE expires<?').run(this.now()-86400000);}
 close(){this.db.close();}
}
