
 PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS users(uuid TEXT PRIMARY KEY,name TEXT NOT NULL,created INTEGER NOT NULL,discount TEXT UNIQUE NOT NULL,plus_until INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS issued_codes(hash TEXT PRIMARY KEY);
 CREATE TABLE IF NOT EXISTS challenges(hash TEXT PRIMARY KEY,browser TEXT UNIQUE NOT NULL,expires INTEGER NOT NULL,uuid TEXT,consumed INTEGER NOT NULL DEFAULT 0,accepted INTEGER NOT NULL,terms TEXT NOT NULL,privacy TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,uuid TEXT NOT NULL REFERENCES users(uuid),expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS consent(uuid TEXT NOT NULL,accepted INTEGER NOT NULL,terms TEXT NOT NULL,privacy TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS nonces(nonce TEXT PRIMARY KEY,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS server_status(id INTEGER PRIMARY KEY CHECK(id=1),payload TEXT NOT NULL,received INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,uuid TEXT NOT NULL REFERENCES users(uuid),days INTEGER NOT NULL,amount INTEGER NOT NULL,discounted INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'creating',provider_id TEXT UNIQUE,payment_id TEXT UNIQUE,created INTEGER NOT NULL,delivery_until INTEGER,delivered INTEGER,consented INTEGER NOT NULL);
 CREATE UNIQUE INDEX IF NOT EXISTS one_discount_per_player ON orders(uuid) WHERE discounted=1;
 CREATE INDEX IF NOT EXISTS orders_by_user ON orders(uuid,created);
 CREATE INDEX IF NOT EXISTS delivery_queue ON orders(status,created);
 CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
 
CREATE TABLE IF NOT EXISTS game_profiles(uuid TEXT PRIMARY KEY,name TEXT NOT NULL,name_search TEXT NOT NULL,payload TEXT NOT NULL,updated INTEGER NOT NULL);
 CREATE INDEX IF NOT EXISTS game_profile_search ON game_profiles(name_search);
 CREATE TABLE IF NOT EXISTS game_presence(uuid TEXT PRIMARY KEY,role TEXT NOT NULL,captured INTEGER NOT NULL,inventory TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS game_private(uuid TEXT PRIMARY KEY,punishments TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS staff_roster(uuid TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS staff_sync(id INTEGER PRIMARY KEY CHECK(id=1),received INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS stats_sync(id INTEGER PRIMARY KEY CHECK(id=1),received INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS game_season(id INTEGER PRIMARY KEY CHECK(id=1),current INTEGER NOT NULL,next INTEGER NOT NULL,phase TEXT NOT NULL,changed INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS moderation_audit(actor TEXT NOT NULL,target TEXT NOT NULL,action TEXT NOT NULL,created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS upi_attempts(
 id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),amount INTEGER NOT NULL,
 rate REAL NOT NULL,rate_date TEXT NOT NULL,created INTEGER NOT NULL,expires INTEGER NOT NULL,
 cancelled INTEGER NOT NULL DEFAULT 0,bank_reference TEXT UNIQUE,settled INTEGER,received INTEGER,
 late_accepted INTEGER NOT NULL DEFAULT 0);
 CREATE INDEX IF NOT EXISTS upi_order ON upi_attempts(order_id,created);