'use client';
import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {Crown,ShieldCheck,Shield,Users,X,RefreshCw} from 'lucide-react';
const ROLES=[{key:'all',label:'Everyone',Icon:Users},{key:'owner',label:'Owner',Icon:Crown},{key:'admin',label:'Admin',Icon:ShieldCheck},{key:'mod',label:'Mod',Icon:Shield}];
export default function StaffOverlay({open,onClose}){
 const dialog=useRef(null),[filter,setFilter]=useState('all'),[roster,setRoster]=useState(null),[error,setError]=useState('');const reduce=useReducedMotion();
 useEffect(()=>{if(!open)return;dialog.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[open]);
 useEffect(()=>{if(!open)return;const abort=new AbortController();let busy=false;setError('');setRoster(null);const refresh=async()=>{if(busy)return;busy=true;try{const response=await fetch('/api/staff',{cache:'no-store',signal:abort.signal});if(!response.ok)throw Error();const data=await response.json();if(!Array.isArray(data.members))throw Error();setRoster(data);setError('');}catch(e){if(e.name!=='AbortError'){setRoster(null);setError('The staff list is temporarily unavailable. Try again shortly.');}}finally{busy=false;}};refresh();const timer=setInterval(refresh,5000);return()=>{clearInterval(timer);abort.abort();};},[open]);
 const members=(roster?.members||[]).filter(p=>filter==='all'||p.role===filter);
 return <AnimatePresence>{open&&<motion.dialog ref={dialog} className="staff-overlay" aria-labelledby="staff-heading" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===dialog.current)onClose();}} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduce?0:.18}}><motion.div className="staff-sheet" initial={{y:reduce?0:26,scale:reduce?1:.97}} animate={{y:0,scale:1}} exit={{y:reduce?0:14}} transition={{duration:reduce?0:.25}}><div className="staff-sheet-top"><span className="eyebrow">THE NUGGET SMP TEAM</span><button className="icon-button" aria-label="Close staff overlay" onClick={onClose} autoFocus><X/></button></div><h2 id="staff-heading">Behind the <em>server.</em></h2><p>Need a hand? These are the people to look for in-game.</p><div className="staff-filters" role="group" aria-label="Filter staff by rank">{ROLES.map(({key,label,Icon})=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}><Icon size={17}/>{label}<small>{(roster?.members||[]).filter(p=>key==='all'||p.role===key).length}</small></button>)}</div><div className="staff-roster" aria-live="polite">{error?<p className="staff-empty">{error}</p>:!roster?<p className="staff-empty">Loading the team…</p>:roster.stale?<p className="staff-empty">Waiting for a fresh roster from the server.</p>:members.length?members.map(p=>{const {Icon,label}=ROLES.find(r=>r.key===p.role);return <motion.article layout={!reduce} className={'staff-person role-'+p.role} key={p.uuid} initial={{opacity:0,y:reduce?0:8}} animate={{opacity:1,y:0}}><img src={'https://crafthead.net/avatar/'+p.uuid+'/96'} alt={p.name+' Minecraft face'} width="64" height="64" loading="lazy"/><div><h3>{p.name}</h3><span><Icon size={14}/>{label}</span></div><Icon className="staff-watermark" size={38}/></motion.article>;}):<p className="staff-empty">No {filter==='all'?'staff':ROLES.find(r=>r.key===filter).label.toLowerCase()+'s'} currently assigned.</p>}</div><footer className="staff-sheet-footer"><span><RefreshCw size={13}/>Synced with in-game roles</span><a href="/moderation/">Staff sign-in ↗</a></footer></motion.div></motion.dialog>}</AnimatePresence>;
}
