'use client';
import SeasonBanner from './season';
import StaffOverlay from './staff';
import {useEffect,useState} from 'react';
import {Search,ArrowLeft,Shield,Swords,Coins,Clock,TrendingUp,TrendingDown,Users,RefreshCw,Box,FileWarning,Sun,Moon} from 'lucide-react';
const titles={crystal:'Crystal',sword:'Sword',mace:'Mace',spear_mace:'Spear Mace',netherite_pot:'Netherite Potion',axe:'Axe',uhc:'UHC',sumo:'Sumo'};
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
const playtime=ms=>{const m=Math.floor(ms/60000);return `${Math.floor(m/1440)}d ${Math.floor(m%1440/60)}h ${m%60}m`;};
const ratio=r=>r.losses?(r.wins/r.losses).toFixed(2):r.wins?'∞':'—';
async function read(path,signal){const r=await fetch('/api'+path,{credentials:'same-origin',cache:'no-store',signal});let d;try{d=await r.json();}catch{throw Error('The game connection is not available on this preview.');}if(!r.ok)throw Error(d.error||'Could not load stats.');return d;}
export default function StatsPage({moderation=false}){
 const [staffOpen,setStaffOpen]=useState(false);
 const [query,setQuery]=useState(''),[players,setPlayers]=useState([]),[selected,setSelected]=useState(null),[profile,setProfile]=useState(null),[error,setError]=useState(''),[staff,setStaff]=useState(null),[inspector,setInspector]=useState(null),[theme,setTheme]=useState('dark'),[loading,setLoading]=useState(true),[page,setPage]=useState(0);
 useEffect(()=>{const theme=localStorage.getItem('nugget-theme')||'dark';setTheme(theme);document.documentElement.dataset.theme=theme;},[]);
 useEffect(()=>{if(!moderation)return;const controller=new AbortController();const refresh=()=>read('/moderation/me',controller.signal).then(s=>{setStaff(s);setError('');}).catch(e=>{if(e.name!=='AbortError'){setStaff(null);setInspector(null);setPlayers([]);setProfile(null);setError(e.message);}});refresh();const timer=setInterval(refresh,5000);return()=>{clearInterval(timer);controller.abort();};},[moderation]);
 useEffect(()=>{if(moderation&&!staff){setLoading(false);return;}const controller=new AbortController();let timer;const refresh=()=>read('/stats?q='+encodeURIComponent(query)+'&page='+page,controller.signal).then(d=>{setPlayers(d.players);setError('');setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});const debounce=setTimeout(()=>{refresh();timer=setInterval(refresh,5000);},250);return()=>{clearTimeout(debounce);clearInterval(timer);controller.abort();};},[query,page,moderation,!!staff]);
 useEffect(()=>{if(!selected||moderation&&!staff)return;const controller=new AbortController();setProfile(null);const refresh=()=>read('/stats/'+selected,controller.signal).then(setProfile).catch(e=>{if(e.name!=='AbortError'){setProfile(null);setError(e.message);}});refresh();const timer=setInterval(refresh,5000);return()=>{clearInterval(timer);controller.abort();};},[selected,moderation,!!staff]);
 const inspect=async kind=>{try{const data=await read('/moderation/'+profile.uuid+'/'+kind);setInspector({kind,...data});}catch(e){setInspector(null);setError(e.message);}};
 useEffect(()=>{const reset=()=>{setProfile(null);setPlayers([]);setSelected(null);setInspector(null);setPage(0);};window.addEventListener('nugget-season',reset);return()=>window.removeEventListener('nugget-season',reset);},[]);
 const choose=p=>{setSelected(p.uuid);setProfile(p);setInspector(null);};
 return <div className="stats-shell"><StaffOverlay open={staffOpen} onClose={()=>setStaffOpen(false)}/><header className="stats-header"><a className="brand" href="/"><img src="/nugget.png" alt=""/>NUGGET SMP</a><nav><a href="/stats/">Players</a><button className="nav-staff" onClick={()=>setStaffOpen(true)}>Staff</button><button className="icon-button" aria-label="Toggle theme" onClick={()=>{const t=theme==='dark'?'light':'dark';setTheme(t);document.documentElement.dataset.theme=t;localStorage.setItem('nugget-theme',t);}}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button></nav></header><SeasonBanner/>
 <main className="stats-main"><a href="/" className="text-button"><ArrowLeft size={15}/>Back to server</a><div className="stats-title"><div><span className="eyebrow">{moderation?'STAFF DESK':'NUGGET SMP / PLAYERS'}</span><h1>{moderation?'Player moderation':'Player stats'}<span>.</span></h1><p>{moderation?staff?`Signed in as ${staff.name} · ${staff.role}`:'Log in on the home page, then join the server with your staff account.':'Balances, playtime and arena rankings. Direct from the server. Every five ranked wins earns 100 Nuggets.'}</p></div><span className="sync-label"><RefreshCw size={14}/>Refreshes every 5s</span></div>
 {error&&<p role="alert" className="error">{error}</p>}
 {(!moderation||staff)&&<><div className="stats-search"><Search size={21}/><input aria-label="Search all players" placeholder="Search a player’s name…" value={query} autoComplete="off" onChange={e=>{setQuery(e.target.value);setPage(0);}}/><span>{query?'Search profiles':'All players'}</span></div><div className="stats-layout"><aside className="player-list" aria-label="Player search results"><h2><Users size={17}/>{query?'Search results':'Player directory'}</h2>{loading?<p>Loading server data…</p>:players.length?players.map(p=><button key={p.uuid} className={selected===p.uuid?'player-result selected':'player-result'} onClick={()=>choose(p)}><img src={'https://crafthead.net/avatar/'+p.uuid+'/48'} alt="" loading="lazy"/><span><strong>{p.name}</strong><small><i className={'presence '+(p.online?'online':'')}/>{p.online?'Online':p.serverStatusKnown?'Offline':'Status unavailable'}</small></span><b>{p.ratings.overall.elo}</b></button>):<p>{query?'No matching players. Try the start of their username.':'No profiles have synced yet. Saved profiles stay available when players go offline.'}</p>}<div className="stats-pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><button disabled={players.length<24} onClick={()=>setPage(page+1)}>Next</button></div></aside>
 <section className="player-detail" aria-live="polite">{profile?<><div className="profile-banner"><img className="player-render" src={'https://crafthead.net/body/'+profile.uuid+'/160'} alt={profile.name+' Minecraft skin'} onError={e=>{e.currentTarget.hidden=true;}}/><div><span className={'tier-badge tier-'+profile.ratings.overall.tier.toLowerCase()}>◆ {profile.ratings.overall.tier} tier · #{profile.globalRank}</span><h2>{profile.name}</h2><p><i className={'presence '+(profile.online?'online':'')}/>{profile.online?'Online':profile.serverStatusKnown?'Offline':'Connection not current'}{!profile.online&&<> · Last seen {new Date(profile.lastSeen).toLocaleString()}</>}</p><small>{profile.stale?'Saved snapshot':'Updated'} · {new Date(profile.syncedAt).toLocaleTimeString()}</small></div></div>
 <div className="metric-grid"><Metric Icon={Coins} title="Money" value={money(profile.money)}/><Metric Icon={Coins} title="Nuggets" value={profile.nuggets.toLocaleString()}/><Metric Icon={Clock} title="Playtime" value={playtime(profile.playtime)}/><Metric Icon={TrendingUp} title="Earned · 7 days" value={money(profile.earned7d)}/><Metric Icon={TrendingDown} title="Spent · 7 days" value={money(profile.spent7d)}/><Metric Icon={Swords} title="Global Elo" value={profile.ratings.overall.elo}/></div>
 <div className="match-summary"><span><strong>{profile.ratings.overall.wins}</strong> Ranked wins</span><span><strong>{profile.ratings.overall.losses}</strong> Ranked losses</span><span><strong>{ratio(profile.ratings.overall)}</strong> W/L ratio</span></div>
 <div className="kit-table"><h3>Kit ratings</h3><p className="reward-progress">Next 100 Nuggets: {(profile.rewardWins||0)%5} / 5 ranked wins. Arena and RTP wins count together.</p><div className="kit-row kit-heading"><span>Kit</span><span>Elo</span><span>W / L</span><span>Tier</span></div>{Object.entries(titles).map(([key,title])=>{const r=profile.ratings[key];return <div className="kit-row" key={key}><span>{title}</span><b>{r.elo}</b><span>{r.wins} / {r.losses}</span><span className={'tier-text tier-'+r.tier.toLowerCase()}>{r.tier}</span></div>;})}</div>
 {moderation&&staff&&<div className="staff-inspection"><h3><Shield size={18}/>Staff inspection</h3><div className="payment-methods"><button className="outline-button" onClick={()=>inspect('punishments')}><FileWarning size={16}/>Punishment history</button><button className="outline-button" onClick={()=>inspect('inventory')}><Box size={16}/>Inventory snapshot</button></div>{inspector?.kind==='inventory'&&<><p>Read-only · {inspector.captured?new Date(inspector.captured).toLocaleTimeString():'player offline or snapshot unavailable'}</p><div className="inventory-snapshot">{inspector.items?.map(i=><div key={i.slot}><small>Slot {i.slot}</small><strong>{i.item.replaceAll('_',' ')}</strong><span>×{i.amount}</span></div>)}</div></>}{inspector?.kind==='punishments'&&(inspector.punishments.length?<ul className="punishments">{inspector.punishments.map(p=><li key={p.id}><strong>Strike {p.strike} · {p.reason}</strong><span>{new Date(p.created).toLocaleString()} · {p.revoked?'Revoked':p.expires>Date.now()?'Active':'Expired'}</span></li>)}</ul>:<p>No recorded punishments.</p>)}</div>}
 </>:<div className="profile-empty"><Swords size={42}/><h2>Find your name.</h2><p>Select a player or search by name. Offline profiles stay available. Stats appear after the game server connects.</p></div>}</section></div><p className="stats-note">Ranked arena results affect Elo. Practice duels do not. Financial totals exclude opening balances and admin adjustments. Skin renders are served by CraftHead.</p></>}
 </main></div>;
}
function Metric({Icon,title,value}){return <article className="metric"><span><Icon size={16}/>{title}</span><strong>{value}</strong></article>;}
